infractiuni = ['--alte infracțiuni(-)', '--446, operațiuni privind circulația drogurilor(art.2 din Legea 143/2000)',
               '--447, import/export de droguri (art.3 din Legea nr. 143/2000)',
               '--448, droguri pentru consum propriu(art.4 din Legea nr. 143/2000)',
               '--449, infracțiuni prevăzute în Legea nr. 194/2011(Legea nr. 194/2011)', '188-Omorul(174)',
               '189-Omorul calificat(175, 176)', '190-Uciderea la cererea victimei(…)',
               '191-Determinarea sau înlesnirea sinuciderii(179)', '192-Uciderea din culpă(178)',
               '193-Lovirea sau alte violenţe(180)', '194-Vătămarea corporală (181)',
               '195-Lovirile sau vătămările cauzatoare de moarte (183)', '196 - Vătămarea corporală din culpă (184)',
               '197-Relele tratamente aplicate minorului(306)', '198-Încăierarea(322)',
               '199-Violenţa în familie(180)',
               '200-Uciderea ori vătămarea nou-născutului săvârșită de către mamă(177)',
               '201-Întreruperea cursului sarcinii(185)', '202-Vătămarea fătului(…)',
               '203-Lăsarea fără ajutor a unei persoane aflate în dificultate(315, 316)',
               '204-Împiedicarea ajutorului(…)', '205-Lipsirea de libertate în mod ilegal(189)',
               '206-Ameninţarea (193)', '207-șantajul (194)', '208-Hărţuirea(…)', '209-Sclavia (190)',
               '210-Traficul de persoane (12 L 678/2001)', '211-Traficul de minori (13 L678/2001)',
               '212-Supunerea la muncă forţată sau obligatorie (191)', '213-Proxenetismul (329)',
               '214-Exploatarea cerșetoriei(…)', '215-Folosirea unui minor în scop de cerșetorie (…)',
               '216-Folosirea serviciilor unei persoane exploatate (…)',
               '217-Sancţionarea tentativei la traficul și exploatarea persoanelor vulnerabile(…)', '218-Violul(197)',
               '219-Agresiunea sexuală (…)', '220-Actul sexual cu un minor(198)',
               '221-Coruperea sexuală a minorilor(202)', '222-Racolarea minorilor în scopuri sexuale(…)',
               '223-Hărţuirea sexuală(203 (1))', '224-Violarea de domiciliu (192)',
               '225-Violarea sediului profesional (…)', '226-Violarea vieţii private(…)',
               '227-Divulgarea secretului profesional (196)', '228-Furtul (208 alin. 1-3)',
               '229-Furtul calificat(209)', '230-Furtul în scop de folosinţă(208 alin. 4)',
               '231-Furturi la plângere prealabilă și împăcarea (210)', '232-Sancţionarea tentativei la furt(222)',
               '233-Tâlhăria(211)', '234-Tâlhăria calificată(211)', '235-Pirateria(212)',
               '236-Tâlhăria sau pirateria urmată de moartea victimei(212)',
               '237-Sancţionarea tentativei la tâlhărie și piraterie (222)', '238-Abuzul de încredere (213)',
               '239-Abuzul de încredere prin fraudarea creditorilor (…)',
               '240-Bancruta simplă(143 alin. 1 L 85/2006)', '241-Bancruta frauduloasă(143 alin. 2 L 85/2006)',
               '242-Gestiunea frauduloasă(214)', '243-Însușirea bunului găsit sau ajuns din eroare la făptuitor(216)',
               '244-Înșelăciunea(215)', '245-Înșelăciunea privind asigurările(…)',
               '246-Deturnarea licitaţiilor publice(…)',
               '247-Exploatarea patrimonială a unei persoane vulnerabile(…)',
               '248-Sancţionarea tentativei la infracțiuni contra patrimoniului prin nesocotirea încrederii (222)',
               '249-Frauda informatică(44 L 161/2003)',
               '250-Efectuarea de operaţiuni financiare în mod fraudulos(27 L 365/2002)',
               '251-Acceptarea operaţiunilor financiare efectuate în mod fraudulos (28 L 365/2002)',
               '252-Sancţionarea tentativei la fraude comise prin sisteme informatice și mijloace de plată electronice(…)',
               '253-Distrugerea (253/217)(217)', '254-Distrugerea calificată(218)',
               '255-Distrugerea din culpă (255/219)(219)', '256-Tulburarea de posesie(220)', '257-Ultrajul(239)',
               '258-Uzurparea de calităţi oficiale(240)', '259-Sustragerea sau distrugerea de înscrisuri (242)',
               '260-Ruperea de sigilii(243)', '261-Sustragerea de sub sechestru(244)',
               '262-Trecerea frauduloasă a frontierei de stat(70 OUG 105/2001)',
               '263-Traficul de migranţi (71 OUG 105/2001)',
               '264-Facilitarea șederii ilegale în România(141 OUG194/2002)',
               '265-Sustragerea de la măsurile de îndepărtare de pe teritoriul României (138 OUG 194/2002)',
               '266-Nedenunţarea(262)', '267-Omisiunea sesizării(263)',
               '268-Inducerea în eroare a organelor judiciare (259)', '269-Favorizarea făptuitorului(264)',
               '270-Tăinuirea (221)', '271-Obstrucţionarea justiţiei(…)', '272-Influenţarea declaraţiilor(261)',
               '273-Mărturia mincinoasă (260)', '274-Răzbunarea pentru ajutorul dat justiţiei (…)',
               '275-Sustragerea sau distrugerea de probe ori de înscrisuri (272)', '276-Presiuni asupra justiţiei(…)',
               '277-Compromiterea intereselor justiţiei(…)', '278-Încălcarea solemnităţii ședinţei (…)',
               '279-Ultrajul judiciar(272 (1))', ' 280-Cercetarea abuzivă(266)',
               '281-Supunerea la rele tratamente (267)', '282-Tortura(267 (1))', '283-Represiunea nedreaptă(268)',
               '284-Asistenţa și reprezentarea neloială(…)', ' 285-Evadarea(269)', '286-Înlesnirea evadării(270)',
               '287-Nerespectarea hotărârilor judecătorești(271)', '288-Neexecutarea sancţiunilor penale (…)',
               '289-Luarea de mită(254)', '290-Darea de mită(255)', '291-Traficul de influenţă(257)',
               '292-Cumpărarea de influenţă(6 (1) L 78/2000)',
               '293-Fapte săvârșite de către membrii instanţelor de arbitraj sau în legătură cu aceștia(…)',
               '294-Fapte săvârșite de către funcţionari străini sau în legătură cu aceștia(…)',
               '295-Delapidarea(215 (1))', '296-Purtarea abuzivă(250)',
               '297-Abuzul în serviciu(246, 247, 248, 248 (1))', '298-Neglijenţa în serviciu(249)',
               '299-Folosirea abuzivă a funcţiei în scop sexual (…)', '300-Uzurparea funcţiei(…)',
               '301-Conflictul de interese(253 (1))', '302-Violarea secretului corespondenţei(195)',
               '303-Divulgarea informaţiilor secrete de stat(169)',
               '304-Divulgarea informaţiilor secrete de serviciu sau nepublice(196)',
               '305-Neglijenţa în păstrarea informaţiilor(252)', '306-Obţinerea ilegală de fonduri (…)',
               '307-Deturnarea de fonduri(302 (1))',
               '308-Infracţiuni de corupţie și de serviciu comise de alte persoane (308/258)(258)',
               '309-Faptele care au produs consecinţe deosebit de grave(…)', '310-Falsificarea de monede(282)',
               '311-Falsificarea de titluri de credit sau instrumente de plată(282)',
               '312-Falsificarea de timbre sau efecte poștale(283)',
               '313-Punerea în circulaţie de valori falsificate (282)',
               '314-Deţinerea de instrumente în vederea falsificării de valori(285)',
               '315-Emiterea frauduloasă de monedă(282)', '316-Falsificarea de valori străine(284)',
               '317-Falsificarea de instrumente oficiale(286)', '318-Folosirea instrumentelor false(287)',
               '319-Falsificarea de instrumente de autentificare străine(…)',
               '320-Falsul material în înscrisuri oficiale(288)', '321-Falsul intelectual(289)',
               '322-Falsul în înscrisuri sub semnătură privată (290)', '323-Uzul de fals(291)',
               '324-Falsificarea unei înregistrări tehnice(…)', '325-Falsul informatic(44 L161/2003)',
               '326-Falsul în declaraţii(292)', '327-Falsul privind identitatea(293)',
               '328-Infracţiuni de fals comise în legătură cu autoritatea unui stat străin(…)',
               '329-Neîndeplinirea îndatoririlor de serviciu sau îndeplinirea lor defectuoasă(274)',
               '330-Neîndeplinirea îndatoririlor de serviciu sau îndeplinirea lor defectuoasă din culpă(273)',
               '331-Părăsirea postului și prezenţa la serviciu sub influenţa alcoolului sau a altor substanţe (275)',
               '332-Distrugerea sau semnalizarea falsă (332/276)(276)', '333-Accidentul de cale ferată(277)',
               '334-Punerea în circulaţie sau conducerea unui vehicul neînmatriculat (85 OUG 195/2002)',
               '335-Conducerea unui vehicul fără permis de conducere(86 OUG 195/2002)',
               '336-Conducerea unui vehicul sub influenţa alcoolului sau a altor substanţe(87 OUG 195/2002)',
               '337-Refuzul sau sustragerea de la prelevarea de mostre biologice(87 OUG 195/2002)',
               '338-Părăsirea locului accidentului ori modificarea sau ștergerea urmelor acestuia(89 OUG 195/2002)',
               '339-Împiedicarea sau îngreunarea circulaţiei pe drumurile publice(92 OUG 195/2002)',
               '340-Nerespectarea atribuţiilor privind verificarea tehnică ori efectuarea reparaţiilor (93 OUG 195/2002)',
               '341-Efectuarea de lucrări neautorizate în zona drumului public(94 OUG 195/2002)',
               '342-Nerespectarea regimului armelor și al muniţiilor (279)',
               '343-Uzul de armă fără drept (133, 135 L 295/2004)',
               '344-Falsificarea sau modificarea. ștergerea sau modificarea marcajelor de pe arme letale (136 L 295/2004)',
               '345-Nerespectarea regimului materialelor nucleare sau al altor materii radioactive (279 (1))',
               '346-Nerespectarea regimului materiilor explozive(280)',
               '347-Sancţionarea tentativei la nerespectarea regimului armelor, munițiilor, materialelor nucleare și al materialelor explozive(…)',
               '348-Exercitarea fără drept a unei profesii sau activităţi(281)',
               '349-Neluarea măsurilor legale de securitate și sănătate în muncă (37 L 319/2006)',
               '350-Nerespectarea măsurilor legale de securitate și sănătate în muncă(38 L 319/2006)',
               '351-Camăta(…)', '352-Zădărnicirea combaterii bolilor(308)', '353-Contaminarea venerică(309)',
               '354-Transmiterea sindromului imunodeficitar dobândit(309)',
               '355-Răspândirea bolilor la animale sau plante (310)', '356-Infectarea apei(311)',
               '357-Falsificarea sau substituirea de alimente ori alte produse(313)',
               '358-Comercializarea de produse alterate(313)', '359-Traficul de produse sau substanţe toxice (312)',
               '360-Accesul ilegal la un sistem informatic(42 L 161/2003)',
               '361-Interceptarea ilegală a unei transmisii de date informatice(43 L 161/2003)',
               '362-Alterarea integrităţii datelor informatice (44 alin. 1 L 161/2003)',
               '363-Perturbarea funcţionării sistemelor informatice (45 L 161/2003)',
               '364-Transferul neautorizat de date informatice(44 alin. 2, 3 L 161/2003)',
               '365-Operaţiuni ilegale cu dispozitive sau programe informatice (46 L 161/2003)',
               '366-Sancţionarea tentativei la infracțiuni contra siguranței și integrității sistemelor și datelor informatice(47 L 161/2003)',
               '367-Constituirea unui grup infracţional organizat (323)', ' 368-Instigarea publică(324)',
               '369-Incitarea la ură sau discriminare(317)',
               '370-Încercarea de a determina săvârșirea unei infracţiuni(…)',
               '371-Tulburarea ordinii și liniștii publice(321)',
               '372-Portul sau folosirea fără drept de obiecte periculoase(2 L 61/1991)',
               '373-Împiedicarea desfășurării unei adunări publice (29 L 60/1991)', ' 374-Pornografia infantilă(325)',
               '375-Ultrajul contra bunelor moravuri (321)', '376-Bigamia(303)', '377-Incestul(203)',
               '378-Abandonul de familie (305)', '379-Nerespectarea măsurilor privind încredinţarea minorului (307)',
               '380-Împiedicarea accesului la învăţământul general obligatoriu(…)',
               '381-Împiedicarea exercitării libertăţii religioase (318)',
               '382-Profanarea lăcașurilor sau a obiectelor de cult (…)',
               '383-Profanarea de cadavre sau morminte (319)',
               '384-Prelevarea ilegală de ţesuturi sau organe(156 L 95/2006)',
               '385-Împiedicarea exercitării drepturilor electorale (52 L 35/2008, 107 L 67/2004, 57 L 370/2004, 55 L 33/2007, 52 L 3/2000)',
               '386-Coruperea alegătorilor(55 L 35/2008, 109 L 67/2004, 58 L 370/2004, 58 L 33/2007, 54 L 3/2000)',
               '387-Frauda la vot(56 L 35/2008, 110 L 67/2004, 59 L 370/2004, 56, 59, 60 L 33/2007, 55 L 3/2000)',
               '388-Frauda la votul electronic(14 OUG 93/2003)',
               '389-Violarea confidenţialităţii votului(54 L 35/2008, 108 L 67/2004, 60 L 370/2004, 57 L 33/2007, 53 L 3/2000)',
               '390-Nerespectarea regimului urnei de vot(59 L 35/2008, 112, 113 L 67/2004, 61 L 370/2004, 62 L 33/2007, 57 L 3/2000))',
               '391-Falsificarea documentelor și evidenţelor electorale(53, 57 alin. 1 L 35/2008, 106 alin. 2 L 67/2004, 62 L 370/2004, 56, 60 L 33/2007, 55 L 3/2000)',
               '392-Fapte săvârșite în legătură cu un referendum(…)',
               '393-Sancţionarea tentativei la infracțiuni electorale (…)',
               '394-412-Infracţiuni contra securităţii naţionale(155-161, 163, 166, 168-173, 356, 19 L51/1991)',
               '413-445-Infracţiuni contra capacităţii de luptă a forţelor armate (331-351)']

msj_inceput = """Fie pentru că nu știu cum să fac, fie că nu se poate se face altfel, înainte de a rula programul ăsta asigurați-vă de următoarele aspecte în ceea ce privește hotărârea penală:
1. Salvați documentele cu sentințele penale în docx (ele vin de pe ECRIS în doc)
2. Dacă nu există ’ROMÂNIA’ scrieți cuvântul deasupra instanței
3. Între ’ROMÂNIA’ și numele instanței ștergeți orice caracter (Dacă e nr dos tăiați si puneți dedesubtul instanței)
4. Ștergeți ’Secția penală’
5. Înainte de fiul/fiica deschideți o paranteza
6. Intre data nașterii și locul nașterii ștergeți „ , ”
7. La CNP, ștergeți ',' dintre sector și CNP (la dispozitiv)
8. Pentru articol scrieți întreg cuvântul "articol" cu litere mici în dispozitiv și puneți o pauză între „articol” și numărul acestuia
(!Momentan articolul se referă doar la Codul Penal, nu alte legi penale. Pentru aceste articole copiați-le direct din sentință)

Succes,

Alex Manole
"""

obligatii = ['să urmeze un curs de pregătire școlară ori de calificare profesională',
             'să presteze o muncă neremunerată în folosul comunităţii, pe o perioadă cuprinsă între 30 și 60 de zile',
             'să presteze o muncă neremunerată în folosul comunităţii, pe o perioadă cuprinsă între 60 și 120 de zile',
             'să frecventeze unul sau mai multe programe de reintegrare socială derulate de către serviciul de probaţiune sau organizate în colaborare cu instituţii din comunitate',
             'să se supună măsurilor de control, tratament sau îngrijire medicală',
             'să nu comunice cu victima sau cu membri de familie ai acesteia, cu persoanele cu care a comis infracţiunea sau cu alte persoane, stabilite de instanţă, ori să nu se apropie de acestea',
             'să nu se afle în anumite locuri sau la anumite manifestări sportive, culturale ori la alte adunări publice, stabilite de instanţă',
             'să nu conducă anumite vehicule stabilite de instanţă',
             'să nu deţină, să nu folosească și să nu poarte nicio categorie de arme',
             'să nu părăsească teritoriul României fără acordul instanţei',
             'să nu ocupe sau să nu exercite funcţia, profesia, meseria ori activitatea de care s-a folosit pentru săvârșirea infracţiunii',
             'fără obligații',
             'să se prezinte la serviciul de probațiune la datele fixate de acesta',
             'să nu depășească, fără acordul serviciului de probațiune, limita teritorială stabilită de instanță', ]

obligatii_sern = {'să urmeze un curs de pregătire școlară ori de calificare profesională': "413",
                  'să presteze o muncă neremunerată în folosul comunităţii, pe o perioadă cuprinsă între 30 și 60 de zile': "414",
                  'să presteze o muncă neremunerată în folosul comunităţii, pe o perioadă cuprinsă între 60 și 120 de zile': "414",
                  'să frecventeze unul sau mai multe programe de reintegrare socială derulate de către serviciul de probaţiune sau organizate în colaborare cu instituţii din comunitate': "415",
                  'să se supună măsurilor de control, tratament sau îngrijire medicală': "416",
                  'să nu comunice cu victima sau cu membri de familie ai acesteia, cu persoanele cu care a comis infracţiunea sau cu alte persoane, stabilite de instanţă, ori să nu se apropie de acestea': "417",
                  'să nu se afle în anumite locuri sau la anumite manifestări sportive, culturale ori la alte adunări publice, stabilite de instanţă': "418",
                  'să nu conducă anumite vehicule stabilite de instanţă': "419",
                  'să nu deţină, să nu folosească și să nu poarte nicio categorie de arme': "420",
                  'să nu părăsească teritoriul României fără acordul instanţei': "421",
                  'să nu depășească, fără acordul serviciului de probațiune, limita teritorială stabilită de instanță': "421",
                  'să nu ocupe sau să nu exercite funcţia, profesia, meseria ori activitatea de care s-a folosit pentru săvârșirea infracţiunii': "422",
                  'să se prezinte la serviciul de probațiune la datele fixate de acesta': "423"
                  }

toate_instantele = {'1': 'Înalta Curte de Casaţie și Justiţie', '2': 'Curtea de Apel București',
                    '3': 'Tribunalul București', '4': 'Judecătoria Sectorului 4 București',
                    '30': 'Tribunalul Timiș', '32': 'Curtea de Apel Bacău',
                    '33': 'Curtea de Apel Cluj', '35': 'Curtea de Apel Oradea', '36': 'Curtea de Apel Constanţa',
                    '39': 'Curtea de Apel Suceava', '40': 'Tribunalul Botoșani', '42': 'Curtea de Apel Ploiești',
                    '43': 'Curtea de Apel Târgu Mureș', '44': 'Curtea de Apel Galaţi', '45': 'Curtea de Apel Iași',
                    '46': 'Curtea de Apel Pitești', '54': 'Curtea de Apel Craiova', '55': 'Judecătoria Arad',
                    '57': 'Curtea de Apel AlbaIulia', '59': 'Curtea de Apel Timișoara', '62': 'Tribunalul Brașov',
                    '63': 'Tribunalul Dolj', '64': 'Curtea de Apel Brașov',
                    '81': 'Curtea Militară de Apel București',
                    '83': 'Tribunalul Satu Mare', '84': 'Tribunalul Sălaj', '85': 'Tribunalul Sibiu',
                    '86': 'Tribunalul Suceava', '87': 'Tribunalul Teleorman', '88': 'Tribunalul Tulcea',
                    '89': 'Tribunalul Vaslui',
                    '90': 'Tribunalul Vâlcea', '91': 'Tribunalul Vrancea', '93': 'Tribunalul Ilfov',
                    '94': 'Judecătoria Buftea', '95': 'Tribunalul Gorj', '96': 'Tribunalul Harghita',
                    '97': 'Tribunalul Hunedoara',
                    '98': 'Tribunalul Ialomiţa', '99': 'Tribunalul Iași', '100': 'Tribunalul Maramureș',
                    '101': 'Tribunalul Mehedinţi', '102': 'Tribunalul Mureș', '103': 'Tribunalul Neamţ',
                    '104': 'Tribunalul Olt',
                    '105': 'Tribunalul Prahova', '107': 'Tribunalul Alba', '108': 'Tribunalul Arad',
                    '109': 'Tribunalul Argeș', '110': 'Tribunalul Bacău', '111': 'Tribunalul Bihor',
                    '112': 'Tribunalul Bistriţa-Năsăud',
                    '113': 'Tribunalul Brăila', '114': 'Tribunalul Buzău', '115': 'Tribunalul Caraș-Severin',
                    '116': 'Tribunalul Călărași', '117': 'Tribunalul Cluj', '118': 'Tribunalul Constanţa',
                    '119': 'Tribunalul Covasna',
                    '120': 'Tribunalul Dâmboviţa', '121': 'Tribunalul Galaţi', '122': 'Tribunalul Giurgiu',
                    '173': 'Judecătoria Adjud', '174': 'Judecătoria Agnita', '175': 'Judecătoria Aiud',
                    '176': 'Judecătoria Alba Iulia',
                    '177': 'Judecătoria Aleșd', '179': 'Judecătoria Babadag', '180': 'Judecătoria Bacău',
                    '181': 'Judecătoria Baia de Aramă', '182': 'Judecătoria Baia Mare',
                    '183': 'Judecătoria Băilești', '184': 'Judecătoria Balș',
                    '185': 'Judecătoria Bălcești', '186': 'Judecătoria Beclean', '187': 'Judecătoria Beiuș',
                    '188': 'Judecătoria Bicaz', '189': 'Judecătoria Bârlad', '190': 'Judecătoria Bistriţa',
                    '191': 'Judecătoria Blaj',
                    '192': 'Judecătoria Bolintin-Vale', '193': 'Judecătoria Botoșani', '195': 'Judecătoria Brad',
                    '196': 'Judecătoria Brăila', '197': 'Judecătoria Brașov', '198': 'Judecătoria Brezoi',
                    '199': 'Judecătoria Buhuși',
                    '200': 'Judecătoria Buzău', '201': 'Judecătoria Calafat', '202': 'Judecătoria Călărași',
                    '203': 'Judecătoria Câmpeni', '204': 'Judecătoria Câmpina', '205': 'Judecătoria Câmpulung',
                    '206': 'Judecătoria Câmpulung Moldovenesc',
                    '207': 'Judecătoria Caracal', '208': 'Judecătoria Caransebeș',
                    '210': 'Judecătoria Chisineu-Cris', '211': 'Judecătoria Cluj-Napoca',
                    '212': 'Judecătoria Constanţa', '213': 'Judecătoria Corabia',
                    '214': 'Judecătoria Costești', '215': 'Judecătoria Craiova',
                    '216': 'Judecătoria Curtea de Argeș', '217': 'Judecătoria Darabani', '218': 'Judecătoria Carei',
                    '219': 'Judecătoria Dej', '220': 'Judecătoria Deta',
                    '221': 'Judecătoria Deva', '222': 'Judecătoria Dorohoi', '223': 'Judecătoria Drăgășani',
                    '224': 'Judecătoria Dragomirești', '225': 'Judecătoria Drobeta-Turnu Severin',
                    '226': 'Judecătoria Făgăraș',
                    '227': 'Judecătoria Fălticeni', '228': 'Judecătoria Făurei', '229': 'Judecătoria Fetești',
                    '230': 'Judecătoria Filiași', '231': 'Judecătoria Focșani', '232': 'Judecătoria Găești',
                    '233': 'Judecătoria Galaţi',
                    '234': 'Judecătoria Gheorgheni', '235': 'Judecătoria Gherla', '236': 'Judecătoria Giurgiu',
                    '237': 'Judecătoria Gura Humorului', '238': 'Judecătoria Gurahonţ', '239': 'Judecătoria Hârlău',
                    '240': 'Judecătoria Haţeg', '241': 'Judecătoria Horezu', '242': 'Judecătoria Huedin',
                    '243': 'Judecătoria Hunedoara', '244': 'Judecătoria Huși', '245': 'Judecătoria Iași',
                    '246': 'Judecătoria Ineu',
                    '247': 'Judecătoria Însurăţei', '248': 'Judecătoria Întorsura Buzăului',
                    '249': 'Judecătoria Lehliu-Gară', '250': 'Judecătoria Lipova', '251': 'Judecătoria Luduș',
                    '252': 'Judecătoria Lugoj',
                    '253': 'Judecătoria Măcin', '254': 'Judecătoria Mangalia', '255': 'Judecătoria Marghita',
                    '256': 'Judecătoria Medgidia', '257': 'Judecătoria Mediaș', '258': 'Judecătoria Miercurea-Ciuc',
                    '259': 'Judecătoria Mizil',
                    '260': 'Judecătoria Moinești', '261': 'Judecătoria Moldova Nouă', '262': 'Judecătoria Moreni',
                    '263': 'Judecătoria Motru', '265': 'Judecătoria Năsăud', '266': 'Judecătoria Negrești-Oaș',
                    '267': 'Judecătoria Novaci',
                    '268': 'Judecătoria Odorheiu Secuiesc', '269': 'Judecătoria Olteniţa',
                    '270': 'Judecătoria Onești', '271': 'Judecătoria Oradea', '272': 'Judecătoria Orăștie',
                    '273': 'Judecătoria Oraviţa', '274': 'Judecătoria Orșova',
                    '275': 'Judecătoria Panciu', '277': 'Judecătoria Pătârlagele', '278': 'Judecătoria Petroșani',
                    '279': 'Judecătoria Piatra-Neamţ', '280': 'Judecătoria Pitești', '281': 'Judecătoria PLOIEŞTI ',
                    '282': 'Judecătoria Pogoanele', '283': 'Judecătoria Pucioasa', '284': 'Judecătoria Răcari',
                    '285': 'Judecătoria Rădăuţi', '286': 'Judecătoria Răducăneni',
                    '287': 'Judecătoria Râmnicu Sărat',
                    '288': 'Judecătoria Râmnicu Vâlcea', '289': 'Judecătoria Reghin', '290': 'Judecătoria Reșiţa',
                    '291': 'Judecătoria Roman', '292': 'Judecătoria Roșiori de Vede', '293': 'Judecătoria Rupea',
                    '294': 'Judecătoria Săliște',
                    '295': 'Judecătoria Sânnicolau Mare', '296': 'Judecătoria Satu Mare',
                    '297': 'Judecătoria Săveni', '298': 'Judecătoria Sebeș',
                    '299': 'Judecătoria Sectorului 1 București', '300': 'Judecătoria Sectorului 2 București',
                    '301': 'Judecătoria Sectorului 3 București', '302': 'Judecătoria Sectorului 5 București',
                    '303': 'Judecătoria Sectorului 6 București', '304': 'Judecătoria Segarcea',
                    '305': 'Judecătoria Sfântu Gheorghe', '306': 'Judecătoria Sibiu',
                    '307': 'Judecătoria Sighetu Marmaţiei', '308': 'Judecătoria Sighișoara',
                    '309': 'Judecătoria Simleu Silvaniei', '310': 'Judecătoria Sinaia',
                    '311': 'Judecătoria Slatina', '312': 'Judecătoria Slobozia', '313': 'Judecătoria Strehaia',
                    '314': 'Judecătoria Suceava', '315': 'Judecătoria Târgoviște', '316': 'Judecătoria Târgu Bujor',
                    '317': 'Judecătoria Târgu Cărbunești', '318': 'Judecătoria Târgu Jiu',
                    '319': 'Judecătoria Târgu Lăpuș', '320': 'Judecătoria Târgu Mureș',
                    '321': 'Judecătoria Târgu-Neamţ', '322': 'Judecătoria Târgu Secuiesc',
                    '323': 'Judecătoria Târnăveni', '324': 'Judecătoria Tecuci', '325': 'Judecătoria Timișoara',
                    '326': 'Judecătoria Topliţa', '327': 'Judecătoria Tulcea',
                    '328': 'Judecătoria Turda', '329': 'Judecătoria Turnu Măgurele', '330': 'Judecătoria Urziceni',
                    '331': 'Judecătoria Vălenii de Munte', '332': 'Judecătoria Vânju Mare',
                    '333': 'Judecătoria Vaslui', '334': 'Judecătoria Vatra Dornei',
                    '335': 'Judecătoria Videle', '336': 'Judecătoria Vișeu de Sus', '337': 'Judecătoria Zalău',
                    '338': 'Judecătoria Zărnești', '339': 'Judecătoria Zimnicea', '739': 'Tribunalul Militar lași',
                    '740': 'Judecătoria Alexandria',
                    '751': 'Tribunalul Militar Timișoara', '752': 'Tribunalul Militar Cluj-Napoca',
                    '753': 'Tribunalul Militar București', '787': 'Judecătoria Avrig',
                    '828': 'Judecătoria Topoloveni', '829': 'Judecătoria Podu Turcului',
                    '832': 'Judecătoria Făget', '833': 'Judecătoria Salonta', '838': 'Judecătoria Liești',
                    '842': 'Judecătoria Hârșova', '847': 'Judecătoria șomcutaMare', '866': 'Judecătoria Pașcani',
                    '1259': 'Tribunalul Comercial Argeș',
                    '1285': 'Tribunalul Comercial Cluj', '1371': 'Tribunalul Comercial Mureș',
                    '1372': 'Tribunalul pentru minori și familie Brașov', '1748': 'Judecătoria Cornetu',
                    '1752': 'Judecătoria Jibou',
                    'P': 'P', 'p': 'P'}

curti_de_apel = {"Curtea de Apel Alba Iulia": "300", "Curtea de Apel Bacau": "301", "Curtea de Apel Brașhov": "302",
                 "Curtea de Apel București": "303", "Curtea de Apel Cluj": "304", "Curtea de Apel Constanța": "305",
                 "Curtea de Apel Craiova": "306",
                 "Curtea de Apel Galați": "307", "Curtea de Apel Iași": "308", "Curtea de Apel Oradea": "309",
                 "Curtea de Apel Pitești": "310",
                 "Curtea de Apel Ploiești": "311", "Curtea de Apel Suceava": "312", "Curtea de Apel Târgu Mureș": "314",
                 "Curtea de Apel Timișoara": "313"}

individualizare = {"Libertate supravegheată": "398",
                   "Suspendarea executării pedepsei sub supraveghere sau sub control": "399",
                   "Amânarea aplicării pedepsei": "400",
                   "Amendă penală înlocuită cu mfc": "401",
                   "Asistarea zilnică": "402",
                   "Consemnarea la sfârșit de săptămână": "403",
                   "Internarea înlocuită": "404",
                   "Liberarea condiţionată": "405",
                   "Liberarea din CE/CD": "406",
                   "Stagiul de formare civică": "407",
                   "Supravegherea": "408",
                   "Suspendarea executării pedepsei": "409"
                   }

jud_orase_dic = {"ADJUD", "AGNITA", "AIUD", "ALBA IULIA", "ALESD", "ALEXANDRIA", "ARAD", "AVRIG", "BABADAG", "BACĂU",
                 "BAIA DE ARAMĂ", "BAIA MARE", "BĂILEșTI", "BĂLCEșTI", "BALȘ", "BÂRLAD", "BECLEAN", "BEIUș", "BICAZ",
                 "BISTRIŢA", "BLAJ",
                 "BOLINTIN VALE", "BOTOșANI", "BRAD", "BRĂILA", "BRAșOV", "BREZOI", "BUFTEA", "BUHUșI", "BUZĂU",
                 "CALAFAT", "CĂLĂRAșI", "CÂMPENI", "CÂMPINA", "CĂMPULUNG",
                 "CÂMPULUNG MOLDOVENESC", "CARACAL", "CARANSEBEș", "CAREI", "CHIșINEU", "CRIș",
                 "CLUJ-NAPOCA", "CONSTANŢA", "CORABIA", "CORNETU", "COSTEșTI", "CRAIOVA",
                 "CURTEA DE ARGEș", "DARABANI", "DEJ", "DETA", "DEVA", "DOROHOI", "DRĂGĂșANI", "DRAGOMIREșTI",
                 "DROBETA-TURNU SEVERIN", "FĂGĂRAș", "FĂGET", "FĂLTICENI", "FĂUREI", "FETEșTI", "FILIAșI", "FOCșANI",
                 "GĂEșTI", "GALAŢI", "GHEORGHENI", "GHERLA", "GIURGIU", "GURA HONŢ", "GURA HUMORULUI", "HÂRLĂU",
                 "HÂRșOVA",
                 "HAŢEG", "HOREZU", "HUEDIN", "HUNEDOARA", "HUșI", "IAșI", "INEU", "ÎNSURĂŢEI",
                 "ÎNTORSURA BUZĂULUI", "JIBOU", "LEHLIUGARA", "LIEșTI", "LIPOVA", "LUDUș", "LUGOJ", "MACIN",
                 "MANGALIA", "MARGHITA", "MEDGIDIA", "MEDIAș", "MIERCUREA CIUC", "MIZIL", "MOINEșTI",
                 "MOLDOVA-NOUĂ", "MORENI", "MOTRU", "NĂSĂUD", "NEGREșTI-OAș", "NOVACI",
                 "ODORHEIUL SECUIESC", "OLTENIŢA", "ONEșTI", "ORADEA", "ORAșTIE", "ORAVIŢA", "ORȘOVA", "PANCIU",
                 "PAșCANI", "PĂTĂRLAGELE", "PETROșANI", "PIATRA-NEAMT", "PITEșTI", "PLOIEȘTI", "PODU TURCULUI",
                 "POGOANELE", "PUCIOASA", "RĂCARI", "RĂDĂUŢI", "RĂDUCĂNENI", "RÂMNICU SARAT", "RÂMNICU VALCEA",
                 "REGHIN", "REșITA", "ROMAN", "ROșIORI DE VEDE",
                 "RUPEA", "SALIșTE", "SALONTA", "SÂNNICOLAUL MARE", "SATU MARE", "SĂVENI", "SEBEș", "SEGARCEA",
                 "SFÂNTU GHEORGHE", "SIBIU", "SIGHETU", "MARMAŢIEI", "SIGHIșOARA", "șIMLEUL SILVANIEI",
                 "SINAIA", "SLATINA", "SLOBOZIA", "STREHAIA", "SUCEAVA", "TÂRGOVIșTE", "TÂRGU-CĂRBUNEșTI",
                 "TÂRGU BUJOR", "TÂRGU JIU", "TÂRGU LAPUș", "TÂRGU MUREș", "TĂRGU NEAMŢ", "TÂRGU SECUIESC",
                 "TÂRNAVENI", "TECUCI", "TIMIșOARA", "TOPLIŢA", "TOPOLOVENI", "TULCEA", "TURDA", "TURNU MĂGURELE",
                 "URZICENI", "VĂLENII DE MUNTE", "VÂNJU MARE", "VASLUI", "VATRA DORNEI", "VIDELE", "VIșEU DE SUS",
                 "ZALĂU",
                 "ZĂRNEșTI", "ZIMNICEA"}
jud_orase = ["ADJUD", "AGNITA", "AIUD", "ALBA IULIA", "ALESD", "ALEXANDRIA", "ARAD", "AVRIG", "BABADAG", "BACĂU",
             "BAIA DE ARAMĂ", "BAIA MARE", "BĂILEșTI", "BĂLCEșTI", "BALș", "BÂRLAD", "BECLEAN", "BEIUș", "BICAZ",
             "BISTRIŢA", "BLAJ",
             "BOLINTIN VALE", "BOTOșANI", "BRAD", "BRĂILA", "BRAșOV", "BREZOI", "BUFTEA", "BUHUșI", "BUZĂU",
             "CALAFAT", "CĂLĂRAșI", "CÂMPENI", "CÂMPINA", "CĂMPULUNG",
             "CÂMPULUNG MOLDOVENESC", "CARACAL", "CARANSEBEș", "CAREI", "CHIșINEU", "CRIș",
             "CLUJ-NAPOCA", "CONSTANŢA", "CORABIA", "CORNETU", "COSTEșTI", "CRAIOVA",
             "CURTEA DE ARGEș", "DARABANI", "DEJ", "DETA", "DEVA", "DOROHOI", "DRĂGĂșANI", "DRAGOMIREșTI",
             "DROBETA-TURNU SEVERIN", "FĂGĂRAș", "FĂGET", "FĂLTICENI", "FĂUREI", "FETEșTI", "FILIAșI", "FOCșANI",
             "GĂEșTI", "GALAŢI", "GHEORGHENI", "GHERLA", "GIURGIU", "GURA HONŢ", "GURA HUMORULUI", "HÂRLĂU", "HÂRșOVA",
             "HAŢEG", "HOREZU", "HUEDIN", "HUNEDOARA", "HUșI", "IAșI", "INEU", "ÎNSURĂŢEI",
             "ÎNTORSURA BUZĂULUI", "JIBOU", "LEHLIUGARA", "LIEșTI", "LIPOVA", "LUDUș", "LUGOJ", "MACIN",
             "MANGALIA", "MARGHITA", "MEDGIDIA", "MEDIAș", "MIERCUREA CIUC", "MIZIL", "MOINEșTI",
             "MOLDOVA-NOUĂ", "MORENI", "MOTRU", "NĂSĂUD", "NEGREșTI-OAș", "NOVACI",
             "ODORHEIUL SECUIESC", "OLTENIŢA", "ONEșTI", "ORADEA", "ORAșTIE", "ORAVIŢA", "ORȘOVA", "PANCIU",
             "PAșCANI", "PĂTĂRLAGELE", "PETROșANI", "PIATRA-NEAMT", "PITEșTI", "PLOIEȘTI", "PODU TURCULUI",
             "POGOANELE", "PUCIOASA", "RĂCARI", "RĂDĂUŢI", "RĂDUCĂNENI", "RÂMNICU SARAT", "RÂMNICU VALCEA",
             "REGHIN", "REșITA", "ROMAN", "ROșIORI DE VEDE",
             "RUPEA", "SALIșTE", "SALONTA", "SÂNNICOLAUL MARE", "SATU MARE", "SĂVENI", "SEBEș", "SEGARCEA",
             "SFÂNTU GHEORGHE", "SIBIU", "SIGHETU", "MARMAŢIEI", "SIGHIșOARA", "șIMLEUL SILVANIEI",
             "SINAIA", "SLATINA", "SLOBOZIA", "STREHAIA", "SUCEAVA", "TÂRGOVIșTE", "TÂRGU-CĂRBUNEșTI",
             "TÂRGU BUJOR", "TÂRGU JIU", "TÂRGU LAPUș", "TÂRGU MUREș", "TĂRGU NEAMŢ", "TÂRGU SECUIESC",
             "TÂRNAVENI", "TECUCI", "TIMIșOARA", "TOPLIŢA", "TOPOLOVENI", "TULCEA", "TURDA", "TURNU MĂGURELE",
             "URZICENI", "VĂLENII DE MUNTE", "VÂNJU MARE", "VASLUI", "VATRA DORNEI", "VIDELE", "VIșEU DE SUS", "ZALĂU",
             "ZĂRNEșTI", "ZIMNICEA"
             ]
