# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\splash.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(734, 379)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 731, 381))
        self.frame.setStyleSheet("QFrame{\n"
                                 "background-color:rgb(37, 59, 64);\n"
                                 "border-radius:10px;\n"
                                 "}\n"
                                 "\n"
                                 "QProgressBar::chunk{\n"
                                 "    background-color: qlineargradient(spread:pad, x1:0, y1:0.482864, x2:1, y2:0.466, stop:0 rgba(37, 59, 64, 255), stop:1 rgba(242, 124, 38, 255));\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.machetapp = QtWidgets.QLabel(self.frame)
        self.machetapp.setGeometry(QtCore.QRect(100, 10, 511, 121))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(72)
        font.setBold(False)
        font.setWeight(50)
        self.machetapp.setFont(font)
        self.machetapp.setStyleSheet("color: rgb(242, 124, 38)")
        self.machetapp.setObjectName("machetapp")
        self.creator_lm = QtWidgets.QLabel(self.frame)
        self.creator_lm.setGeometry(QtCore.QRect(180, 140, 331, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.creator_lm.setFont(font)
        self.creator_lm.setStyleSheet("color: rgb(242, 124, 38)")
        self.creator_lm.setObjectName("creator_lm")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(180, 250, 351, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
                                       "color:rgb(242, 124, 38);\n"
                                       "text-align: center;\n"
                                       "}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.se_incarca = QtWidgets.QLabel(self.frame)
        self.se_incarca.setGeometry(QtCore.QRect(290, 290, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.se_incarca.setFont(font)
        self.se_incarca.setStyleSheet("color: rgb(242, 124, 38)")
        self.se_incarca.setObjectName("se_incarca")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.machetapp.setText(_translate("Form", "<strong>machet</strong>app"))
        self.creator_lm.setText(_translate("Form", "Creator<strong> Listă Machetă</strong>"))
        self.se_incarca.setText(_translate("Form", "se încarcă..."))
